-- Find total number of customers by country
select 
country,
count(customer_key) as total_customers from gold_dim_customers group by country order by total_customers desc;
-- find total number of customers by gender
select 
gender,
count(customer_key) as total_customers from gold_dim_customers group by gender order by total_customers desc;
-- find total product by category
select 
category,
count(product_key) as total_product from gold_dim_product group by category order by total_product desc;

-- what is the avg cost in each category
select 
category,
round(avg(product_cost),0) as avg_cost from gold_dim_product group by category order by avg_cost desc;
-- what is the total revenue generated in each categroy
select 
p.category,
sum(f.sales_amount)as total_revenue
from gold_fact_sales f
left join gold_dim_product p 
on p.product_key = f.product_key
group by p.category
order by total_revenue desc ;

-- find total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold_fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by 
c.cusotmer_key,
c.first_name,
c.last_name
order by total_revenue desc;
-- what is the distribution of sold items across countries
select
c.country,
sum(f.sales_quantity) as total_sold_items
from gold_fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by 
c.country
order by total_sold_items desc;
